name: Android APK Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.DOCSCAN_KEYSTORE_64 }}" | base64 --decode > docscan_keystore.jks

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts

      - name: Assemble Release Bundle
        run: |
          export KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          export KEY_ALIAS=${{ secrets.DOCSCAN_ALIAS }}
          export KEY_PASSWORD=${{ secrets.DOCSCAN_ALIAS_PASSWORD }}
          ./gradlew clean bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.DOCSCAN_KEYSTORE_64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.DOCSCAN_ALIAS }}
          keyPassword: ${{ secrets.DOCSCAN_ALIAS_PASSWORD }}

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_AUTH_JSON_PLAIN_TEXT }}
          packageName: com.rehman.docscan
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          inAppUpdatePriority: 3
          whatsNewDirectory: distribution/whatsNew
